[package]
name = "basm-boj"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.15", features = ["gzip"] }
scraper = "0.23.1"
anyhow = "1"
